#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: iroha-docs-l10n
  description: Iroha Documentation
  homepage: https://wiki.hyperledger.org/display/iroha
  default_branch: default
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
